import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type CartSessionDocument = CartSession & Document;

export enum CartStatus {
  ACTIVE = 'active',
  ABANDONED = 'abandoned',
  CONVERTED = 'converted', // Completed a lead/purchase
}

@Schema({ _id: false })
export class CartItem {
  @Prop({ required: true })
  productId: string;

  @Prop({ required: true })
  quantity: number;

  @Prop({ required: true })
  price: number;
}

@Schema({ timestamps: true })
export class CartSession {
  @Prop({ required: true, unique: true })
  sessionId: string; // Generated by frontend or backend

  @Prop({ required: false })
  userId?: string; // If logged in

  @Prop({ type: [CartItem], default: [] })
  items: CartItem[];

  @Prop({ type: String, enum: CartStatus, default: CartStatus.ACTIVE })
  status: CartStatus;

  @Prop({ required: true, default: 0 })
  totalValue: number;

  @Prop({ type: Date, default: Date.now })
  lastInteraction: Date;
}

export const CartSessionSchema = SchemaFactory.createForClass(CartSession);
